trigger:
- main

pool:
  name: Default

steps:
- script: dotnet build QuizApp/QuizApp.csproj
  displayName: Build .NET app

- script: dotnet publish QuizApp/QuizApp.csproj -o $(Build.ArtifactStagingDirectory)
  displayName: Publish app

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'dotnetapp'
    publishLocation: 'Container'