trigger:
- main

pool:
  name: Default

steps:
- script: echo "Database access has already been done on April 6, 2026 by Kendra Matthews"
  displayName: Show database message

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '.'
    ArtifactName: 'quiz-files'
    publishLocation: 'Container'